### ISSUE TITLE
Not taking input from discord

### ISSUE THREAD

**Issue by TruthSearchers** [ChobPT/text-generation-webui-discord_bot#1]
its not taking input from discord , webhook is connected succesfully 
its only giving all output generated in web ui 

also if you can add image and audio feature for it ,it would be amazing

**Comment by TheMeIonGod** [comment]
It might be because it is a Webhook and not a Bot.

**Comment by TruthSearchers** [comment]
Yeah i know that but if it can take input messages ,also output 
(I am just studying webhooks now so dont know ) but it's for sure images and audio can be added to it

**Comment by ChobPT** [comment]
"Currently it only sends any response from the chatbot to a discord Webhook of your choosing"

Working on the next step, but wanted to launch an initial version for any interested users on using the read only
